### ISSUE TITLE
failure mode in fitter.py  _fit_psf_obslist_trim 

### ISSUE THREAD

**Issue by rgruendl** [esheldon/fitvd#10]
Failure rate was ~3% of DES tiles... (or 3 in 5000 executions).
Traceback is below... my guess is that no "res" is available if all attempts to fit fail (so second half of print statement will not be reconcilable).  Example traceback follows:

Traceback (most recent call last):
  File "/local/stack/eups/packages/Linux64/fitvd/0.9.15SkipPsfFail+0/bin/fitvd", line 52, in <module>
    main()
  File "/local/stack/eups/packages/Linux64/fitvd/0.9.15SkipPsfFail+0/bin/fitvd", line 48, in main
    processor.go()
  File "/local/stack/eups/packages/Linux64/fitvd/0.9.15SkipPsfFail+0/python/fitvd/process.py", line 60, in go
    output, epochs_data, fof_data = self._process_fof(fofid)
  File "/local/stack/eups/packages/Linux64/fitvd/0.9.15SkipPsfFail+0/python/fitvd/process.py", line 107, in _process_fof
    mbobs_list, flags = self._get_fof_mbobs_list(indices)
  File "/local/stack/eups/packages/Linux64/fitvd/0.9.15SkipPsfFail+0/python/fitvd/process.py", line 194, in _get_fof_mbobs_list
    mbobs, flags = self._get_mbobs(index)
  File "/local/stack/eups/packages/Linux64/fitvd/0.9.15SkipPsfFail+0/python/fitvd/process.py", line 402, in _get_mbobs
    show=False,
  File "/local/stack/eups/packages/Linux64/fitvd/0.9.15SkipPsfFail+0/python/fitvd/process.py", line 755, in _subtract_neighbors
    self.rng,
  File "/local/stack/eups/packages/Linux64/fitvd/0.9.15SkipPsfFail+0/python/fitvd/fitting.py", line 1212, in fit_all_psfs_trim
    rng=rng,
  File "/local/stack/eups/packages/Linux64/fitvd/0.9.15SkipPsfFail+0/python/fitvd/fitting.py", line 1195, in _fit_psf_mbobs_trim
    rng=rng,
  File "/local/stack/eups/packages/Linux64/fitvd/0.9.15SkipPsfFail+0/python/fitvd/fitting.py", line 1183, in _fit_psf_obslist_trim
    "in obslist: %s" % str(res))
UnboundLocalError: local variable 'res' referenced before assignment

**Comment by esheldon** [comment]
Thanks robert.  Can you please make a complete test example available?
