### ISSUE TITLE
Error in one single-object fit causes a failure for the whole tile

### ISSUE THREAD

**Issue by madamow** [esheldon/fitvd#13]
This affects DELVE-WIDE and DELVE-DEEP  processing. Here is how the failure manifests in the log file:

```
NFO:fitvd.process:loading config: config/Y6A1_v1_fitvd-Y6A1v5.yaml
INFO:fitvd.process:will mask: ['BPM', 'SATURATE', 'INTERP', 'BADAMP', 'CRAY', 'TRAIL', 'EDGEBLEED', 'EDGE', 'STREAK', 'NEAREDGE', 'TAPEBUMP']
INFO:fitvd.process:combined val: 26335
INFO:fitvd.process:loading meds: meds/DES0821+1209_r5918p02_g_meds-delve.fits.fz
INFO:fitvd.process:loading meds: meds/DES0821+1209_r5918p02_r_meds-delve.fits.fz
INFO:fitvd.process:loading meds: meds/DES0821+1209_r5918p02_i_meds-delve.fits.fz
INFO:fitvd.process:loading meds: meds/DES0821+1209_r5918p02_z_meds-delve.fits.fz
INFO:fitvd.files:loading fofs: sof/DES0821+1209_r6015p02_sof-fofslist.fits
INFO:fitvd.process:processing fof range: 41095:41097
INFO:fitvd.process:processing: 41095:41097
INFO:fitvd.process:FoF size: 1
INFO:fitvd.fitting:guess[0]:   0.0706     0.377   -0.0456     0.038     0.782       0.5       537  2.76e+03  4.14e+03  7.25e+03 
INFO:fitvd.fitting:ntry: 1 nfev: 67
INFO:fitvd.fitting:0 pars:  -0.0151   -0.013   -0.321    0.111    0.149    0.474      431 1.95e+03 3.36e+03 4.45e+03
INFO:fitvd.fitting:0 perr:   0.0141   0.0129    0.109    0.111   0.0326    0.101     47.5     91.4     83.1      143
INFO:fitvd.process:nmasked: 0 fit result: ok
INFO:fitvd.process:FoF time: 11.1832
INFO:fitvd.process:processing: 41096:41097
INFO:fitvd.process:FoF size: 1
Traceback (most recent call last):
  File "/local/stack9/eups/packages/Linux64/fitvd/0.9.18+14/bin///fitvd", line 52, in <module>
    main()
  File "/local/stack9/eups/packages/Linux64/fitvd/0.9.18+14/bin///fitvd", line 48, in main
    processor.go()
  File "/local/stack9/eups/packages/Linux64/fitvd/0.9.18+14/python/fitvd/process.py", line 60, in go
*** Error in `/local/stack9/eups/packages/Linux64/python/no.optimiz.3.7.1+1/bin/python3': free(): invalid next size (normal): 0x00000000046199f0 ***
======= Backtrace: =========
/lib64/libc.so.6(+0x81329)[0x7f432efc5329]
/local/stack9/eups/packages/Linux64/python/no.optimiz.3.7.1+1/lib/libpython3.7m.so.1.0(+0x1f55ac)[0x7f432fe2c5ac]
/local/stack9/eups/packages/Linux64/python/no.optimiz.3.7.1+1/lib/libpython3.7m.so.1.0(_PyMethodDef_RawFastCallDict+0x8d)[0x7f432fcca85d]
/local/stack9/eups/packages/Linux64/python/no.optimiz.3.7.1+1/lib/libpython3.7m.so.1.0(_PyCFunction_FastCallDict+0x28)[0x7f432fccab08]
/local/stack9/eups/packages/Linux64/python/no.optimiz.3.7.1+1/lib/libpython3.7m.so.1.0(_PyObject_CallMethodId_SizeT+0x106)[0x7f432fccbad6]
/local/stack9/eups/packages/Linux64/python/no.optimiz.3.7.1+1/lib/libpython3.7m.so.1.0(+0x1fb044)[0x7f432fe32044]
/local/stack9/eups/packages/Linux64/python/no.optimiz.3.7.1+1/lib/libpython3.7m.so.1.0(_PyMethodDef_RawFastCallDict+0x8d)[0x7f432fcca85d]
/local/stack9/eups/packages/Linux64/python/no.optimiz.3.7.1+1/lib/libpython3.7m.so.1.0(_PyCFunction_FastCallDict+0x28)[0x7f432fccab08]
/local/stack9/eups/packages/Linux64/python/no.optimiz.3.7.1+1/lib/libpython3.7m.so.1.0(_PyObject_CallMethodId+0x106)[0x7f432fccbc56]
/local/stack9/eups/packages/Linux64/python/no.optimiz.3.7.1+1/lib/libpython3.7m.so.1.0(+0x1a03e9)[0x7f432fdd73e9]
/local/stack9/eups/packages/Linux64/python/no.optimiz.3.7.1+1/lib/libpython3.7m.so.1.0(PyTraceBack_Print+0x1b0)[0x7f432fdd7e50]
/local/stack9/eups/packages/Linux64/python/no.optimiz.3.7.1+1/lib/libpython3.7m.so.1.0(+0x192481)[0x7f432fdc9481]
/local/stack9/eups/packages/Linux64/python/no.optimiz.3.7.1+1/lib/libpython3.7m.so.1.0(PyErr_Display+0x6d)[0x7f432fdca40d]
/local/stack9/eups/packages/Linux64/python/no.optimiz.3.7.1+1/lib/libpython3.7m.so.1.0(+0x19c47f)[0x7f432fdd347f]
/local/stack9/eups/packages/Linux64/python/no.optimiz.3.7.1+1/lib/libpython3.7m.so.1.0(_PyMethodDef_RawFastCallDict+0x2e1)[0x7f432fccaab1]
/local/stack9/eups/packages/Linux64/python/no.optimiz.3.7.1+1/lib/libpython3.7m.so.1.0(_PyCFunction_FastCallDict+0x28)[0x7f432fccab08]
/local/stack9/eups/packages/Linux64/python/no.optimiz.3.7.1+1/lib/libpython3.7m.so.1.0(PyErr_PrintEx+0xda)[0x7f432fdca59a]
/local/stack9/eups/packages/Linux64/python/no.optimiz.3.7.1+1/lib/libpython3.7m.so.1.0(PyRun_SimpleFileExFlags+0x2e9)[0x7f432fdcb999]
/local/stack9/eups/packages/Linux64/python/no.optimiz.3.7.1+1/lib/libpython3.7m.so.1.0(+0x1b313f)[0x7f432fdea13f]
/local/stack9/eups/packages/Linux64/python/no.optimiz.3.7.1+1/lib/libpython3.7m.so.1.0(_Py_UnixMain+0x39)[0x7f432fdea389]
/lib64/libc.so.6(__libc_start_main+0xf5)[0x7f432ef66555]
/local/stack9/eups/packages/Linux64/python/no.optimiz.3.7.1+1/bin/python3[0x40108e]
======= Memory map: ========
00400000-00401000 r--p 00000000 00:26 302426504                          /local/stack9/eups/packages/Linux64/python/no.optimiz.3.7.1+1/bin/python3.7
00401000-00402000 r-xp 00001000 00:26 302426504                          /local/stack9/eups/packages/Linux64/python/no.optimiz.3.7.1+1/bin/python3.7
```
@rgruendl  created a sandbox to run it. It can be downloaded from [here](http://deslogin.cosmology.illinois.edu/~rgruendl/DECADE_fitvd/sandbox.tar)

**Comment by esheldon** [comment]
thanks for the report.

However, this is a low level memory issue so it isn't going to be in any of our python code.  There would be no way to catch this error as python itself crashes.

**Comment by esheldon** [comment]
The best way forward might be to skip this object.

**Comment by rgruendl** [comment]
Any advice on how to skip an individual object??  e.g. Is it possible to provide a directive as an input or config to not process FoF #nnnn?

**Comment by esheldon** [comment]
I think you might need to run with special fof ranges that exclude this object

**Comment by rgruendl** [comment]
Yick... that is what I was afraid of.

**Comment by kadrlica** [comment]
@esheldon I dug into this and found that the issue (at least in the first case I investigated) was being caused by a corrupted image (some NaNs in the weight plane and 1e20 values in the image plane). Obviously the solution is to fix the image, but I'm wondering if you also want a check that will allow the code to avoid barfing when it encounters an image with these issues? As best I can tell, the modification would be upstream in the ngmix meadsreader, though I haven't dug deep enough to figure out exactly where...
